### ISSUE TITLE
packages missing metadata needed for node-gyp under modern npm

### ISSUE THREAD

**Issue by chazomaticus** [hayes/unpm#83] opened 2017-01-20 01:13 UTC
I'm actually not sure if the problem is in unpm, clone-packages, or some unpm sub-project maybe, so apologies if I've submitted this against the wrong project.

The basic issue seems to be that modern npm relies on metadata returned from the registry server to determine whether modules need node-gyp building after installing (where it seems it used to determine this just from the package's files alone).  Packages cloned into unpm with clone-packages are missing the metadata (scripts.install in the meta blob for each version) that would tell modern npm what to do.  As a result, depending on what version of npm you're running, npm installing something out of unpm may or may not properly node-gyp build, for packages that require it.

To see the difference I'm talking about, check out the public registry metadata for [hiredis](https://registry.npmjs.com/hiredis).  The relevant bit is here:

```json
{
  "versions": {
    "0.5.0": {
      "scripts": {
        "test": "node test/reader.js && node test/writer.js",
        "install": "node-gyp rebuild"
      }
    }
  }
}
```

Note that it includes node-gyp rebuild at install time.

Now look at the metadata returned by a fresh install of unpm 1.5.0, with hiredis 0.5.0 cloned just now with clone-packages 1.0.0:

```json
{
  "versions": {
    "0.5.0": {
      "scripts": {
        "test": "node test/reader.js && node test/writer.js"
      }
    }
  }
}
```

Here's what happens when you try to install out of this unpm registry with different npm versions (all with `npm --registry http://localhost:8123/ install hiredis`):

* npm 1.4.29: properly kicks off node-gyp rebuild
* npm 2.15.11: properly kicks off node-gyp rebuild
* npm 3.10.10: **no node-gyp rebuild**
* npm 4.1.1: **no node-gyp rebuild**

Note that all versions do the build as expected when installed from the public registry the same way (just `npm install hiredis`).

I've probably made lots of assumptions in this report, so I'm happy to clarify anything or do any other testing you might want.  Thanks!

**Comment by hayes** [comment] 2017-01-20 01:21
interesting, nothing in npm or its dependent modules mutates dnested keys in the package.json, so the issue must happen during publishing.  I'll dig in a bit and see what I can find.  Initially my guess would be clone-packages, or npm not returning all the required meta data when queried by clone packages. I'm sure its something that could be fixed relatively easily.

**Comment by hayes** [comment] 2017-01-20 01:34
So this is in fact a bug in clone packages. If you look at https://github.com/redis/hiredis-node/blob/master/package.json you will notice it does not have an install in its script block.  Cloning it from github, then publishing it to unpm using npm works correctly and you can see the install script in the resulting metadata.  It seems like it is being added by the npm client at publish time.  clone packages was designed to clone packages recursivly, pulling all dependencies into the private registry, which means it needs to support clonging tarball urls, or github repos/shas as well as the normal pulling from another registry.  To do this, it generates the meta data from the package.json inside the package rather than looking at the metadata returned from npm, and therefore misses the install script.  

I think this could be fixed in clone packages by merging the scripts in the package.json with what is in the npm metadata (or just replacing it is probably cleaner).

**Comment by chazomaticus** [comment] 2017-01-20 01:40
Ah, that makes sense, thanks for looking!  Let me know if I should move this over to the clone-packages issue tracker, or if there's anything else I can do.  Thanks!

**Comment by hayes** [comment] 2017-01-20 01:57
Looking into it a bit more, this issue should probably be moved to that repo since it unrelated to unpm.  I don't think I have time to fix this at the moment, and I'm not sure I even have access to publish a fix for clone-packages. I think it may require an update to npm-fetch (a dep of clone packages) It currently is passed the name and version of a module, where version could be a semver, a git sha, a link to a tarball (anything valid as a value in the dependency part of package.json) and returns a stream of the tarball for that package version. This is currently where the metadata from the npm registry is being lost. clone packages itself only deals with tarballs at the moment, and the logic of fetching from npm is abstracted away.  It would require a significant api change to npm-fetch, so its possible the logic would need to be pulled into clone packages instead.  

I am leaving on a trip tomorrow morning, and wont have time to think about this until late next week at the earliest, but if you want to try to get this working yourself I would recommend pulling in this logic from npm-fetch https://github.com/ForbesLindesay/npm-fetch/blob/master/index.js#L36-L67 into clone packages, and calling these methods https://github.com/ForbesLindesay/npm-fetch/blob/master/index.js#L10-L14 directly. 

Then reimplement the one for pulling from npm so that you can persist and use the metadata when publishing to the private registry

**Closed** 2017-01-20 01:57 UTC
